openapi: 3.0.0
info:
  title: FlyAway - Users & Trips Service
  version: 1.0.0
  description: API para autenticación de usuarios y gestión de viajes.
  
servers:
  - url: http://localhost:3001

paths:

  /api/users/register:
    post:
      summary: Register a new user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User created
        '400':
          description: Email already exists

  /api/users/login:
    post:
      summary: Login and get JWT
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login OK
        '400':
          description: Invalid credentials

  /api/trips:
    get:
      summary: Get all trips of authenticated user
      tags:
        - Trips
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of trips
        '401':
          description: Unauthorized

    post:
      summary: Create a new trip
      tags:
        - Trips
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - startDate
                - endDate
              properties:
                name:
                  type: string
                description:
                  type: string
                startDate:
                  type: string
                  format: date
                endDate:
                  type: string
                  format: date
                imageUrl:
                  type: string
                participants:
                  type: array
                  items:
                    type: string
                  description: Emails of participants to add initially (optional)
      responses:
        '201':
          description: Trip created
        '401':
          description: Unauthorized

  /api/trips/{id}:
    get:
      summary: Get a trip by ID
      tags:
        - Trips
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Trip details
        '401':
          description: Unauthorized
        '404':
          description: Trip not found

    put:
      summary: Update a trip by ID
      tags:
        - Trips
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                startDate:
                  type: string
                  format: date
                endDate:
                  type: string
                  format: date
                imageUrl:
                  type: string
      responses:
        '200':
          description: Trip updated
        '401':
          description: Unauthorized
        '404':
          description: Trip not found

    delete:
      summary: Delete a trip by ID
      tags:
        - Trips
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Trip deleted
        '401':
          description: Unauthorized
        '404':
          description: Trip not found

  /api/trips/{id}/participants:
    post:
      summary: Add a participant to a trip
      tags:
        - Participants
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Participant added
        '401':
          description: Unauthorized
        '403':
          description: Only admins can add participants
        '404':
          description: User not found

    get:
      summary: Get all participants of a trip
      tags:
        - Participants
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of participants
        '401':
          description: Unauthorized
        '403':
          description: Only participants can view the list

  /api/trips/{id}/participants/{userId}:
    delete:
      summary: Remove a participant from a trip
      tags:
        - Participants
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Participant removed
        '401':
          description: Unauthorized
        '403':
          description: Only admins can remove participants
        '404':
          description: Participant not found
  
  /api/trips/{id}/participants/{userId}/role:
    patch:
      summary: Change role of a participant (admin/member)
      tags:
        - Participants
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - role
              properties:
                role:
                  type: string
                  enum: [admin, member]
      responses:
        '200':
          description: Role updated
        '401':
          description: Unauthorized
        '403':
          description: Only admins can change roles
        '404':
          description: Participant not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT