openapi: 3.0.0
info:
  title: FlyAway - Users & Trips Service
  version: 1.0.0
  description: API para autenticación de usuarios y gestión de viajes.

servers:
  - url: http://localhost:3001

paths:

  /api/users/register:
    post:
      summary: Register a new user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User created
        '400':
          description: Email already exists

  /api/users/login:
    post:
      summary: Login and get JWT
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login OK
        '400':
          description: Invalid credentials

  /api/trips:
    get:
      summary: Get all trips of authenticated user
      tags:
        - Trips
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of trips
        '401':
          description: Unauthorized

    post:
      summary: Create a new trip
      tags:
        - Trips
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - startDate
                - endDate
              properties:
                name:
                  type: string
                description:
                  type: string
                startDate:
                  type: string
                  format: date
                endDate:
                  type: string
                  format: date
                imageUrl:
                  type: string
      responses:
        '201':
          description: Trip created
        '401':
          description: Unauthorized

  /api/trips/{id}:
    get:
      summary: Get a trip by ID
      tags:
        - Trips
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Trip details
        '401':
          description: Unauthorized
        '404':
          description: Trip not found

    put:
      summary: Update a trip by ID
      tags:
        - Trips
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                startDate:
                  type: string
                  format: date
                endDate:
                  type: string
                  format: date
                imageUrl:
                  type: string
      responses:
        '200':
          description: Trip updated
        '401':
          description: Unauthorized
        '404':
          description: Trip not found

    delete:
      summary: Delete a trip by ID
      tags:
        - Trips
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Trip deleted
        '401':
          description: Unauthorized
        '404':
          description: Trip not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT